version: '3'

services:

  docker-push:
    image: 'tmvdl/projects:nini'
    build: './src'

  github-release:
    image: 'github-release'
    build: './src/www'

  www:
    build: './src/www'
    ports:
      - '80:80'
