version: '3'

services:
  www:
    build: './src'
    volumes:
      - './src/www:/usr/share/nginx/html'
    ports:
      - '80:80'

  docker-push:
    image: 'tmvdl/projects:anagram'
    build: './src/www'

  github-release:
    image: 'github-release'
    build: './src'
