version: '3'

# yes | keytool -genkey -v -alias alias -keystore /builds/keystore.jks -keyalg RSA -storepass password -keypass password -validity 1 -keysize 2048

services:
  app:
    image: tmvdl/android:cordova
    volumes:
      - ./app:/app
      - ./builds:/builds
